# Generated by Django 3.0.4 on 2020-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('total', models.IntegerField(default=0)),
                ('oportunities', models.IntegerField(default=0)),
                ('enable_lessons', models.IntegerField(default=0)),
                ('scheduled_lessons', models.IntegerField(default=0)),
                ('saw_lessons', models.IntegerField(default=0)),
                ('bag', models.IntegerField(default=0)),
            ],
        ),
    ]
