# Generated by Django 3.0.4 on 2020-04-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_det', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise_det',
            old_name='total',
            new_name='total_days',
        ),
    ]
