# Generated by Django 3.0.4 on 2020-04-21 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('exercise', '0002_auto_20200421_1552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise_det', '0002_auto_20200421_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_det',
            name='id_exercise_fk',
            field=models.ForeignKey(blank=True, db_column='id_exercise_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='exercise_det',
            name='id_plan_fk',
            field=models.ForeignKey(blank=True, db_column='id_plan_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
        migrations.AddField(
            model_name='exercise_det',
            name='id_user_fk',
            field=models.ForeignKey(blank=True, db_column='id_customuser_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
