# Generated by Django 3.0.7 on 2020-09-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_det', '0004_exercise_det_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_det',
            name='devolutions',
            field=models.IntegerField(default=0),
        ),
    ]
