# Generated by Django 3.0.7 on 2020-09-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20200614_1543'),
        ('exercise', '0013_auto_20200627_0949'),
        ('exercise_det', '0006_auto_20200905_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_det',
            name='id_exercise_fk',
            field=models.ForeignKey(blank=True, db_column='id_exercise_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AlterField(
            model_name='exercise_det',
            name='id_plan_fk',
            field=models.ForeignKey(db_column='id_plan_fk', on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
    ]
