# Generated by Django 3.0.7 on 2020-06-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_day_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='id_day_fk',
            field=models.ManyToManyField(to='exercise.Day'),
        ),
    ]
