# Generated by Django 3.0.7 on 2020-06-22 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_exercise_id_day_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='id_exercise_fk',
        ),
        migrations.AddField(
            model_name='hour',
            name='id_day_fk',
            field=models.ForeignKey(blank=True, db_column='id_exercise_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Day'),
        ),
    ]
