# Generated by Django 3.0.7 on 2020-06-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20200622_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='id_day_fk',
        ),
        migrations.RemoveField(
            model_name='hour',
            name='id_day_fk',
        ),
        migrations.AddField(
            model_name='hour',
            name='id_exercise_fk',
            field=models.ForeignKey(blank=True, db_column='id_exercise_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='hour',
            name='name',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
