# Generated by Django 3.0.7 on 2020-06-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20200623_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='name',
        ),
    ]
