# Generated by Django 3.0.7 on 2020-06-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_remove_hour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='hour',
            name='hour_chance',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hour',
            name='hour_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hour',
            name='hour_lesson',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hour',
            name='id_day_fk',
            field=models.ForeignKey(db_column='id_day_fk', on_delete=django.db.models.deletion.CASCADE, to='exercise.Day'),
        ),
        migrations.AlterField(
            model_name='hour',
            name='id_exercise_fk',
            field=models.ForeignKey(db_column='id_exercise_fk', on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
    ]
