# Generated by Django 3.0.4 on 2020-04-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0003_auto_20200405_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='money',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='width_field',
        ),
    ]
