# Generated by Django 3.0.4 on 2020-04-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0004_auto_20200405_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ci',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
