# Generated by Django 3.0.4 on 2020-04-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0005_customuser_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
