# Generated by Django 3.0.4 on 2020-04-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0007_auto_20200410_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=28, null=True, unique=True),
        ),
    ]
