# Generated by Django 3.0.4 on 2020-04-29 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20200421_1552'),
        ('plan', '0004_auto_20200429_1205'),
        ('create_user', '0008_auto_20200411_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('total_days', models.IntegerField(default=0)),
                ('oportunities', models.IntegerField(default=0)),
                ('enable_lessons', models.IntegerField(default=0)),
                ('scheduled_lessons', models.IntegerField(default=0)),
                ('saw_lessons', models.IntegerField(default=0)),
                ('bag', models.IntegerField(default=0)),
                ('id_exercise_fk', models.ForeignKey(blank=True, db_column='id_exercise_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise')),
                ('id_plan_fk', models.ForeignKey(blank=True, db_column='id_plan_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
                ('id_user_fk', models.ForeignKey(blank=True, db_column='id_customuser_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
