# Generated by Django 3.0.4 on 2020-04-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0009_exercise_det'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise_det',
        ),
    ]
