# Generated by Django 3.0.6 on 2020-06-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0012_auto_20200605_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise_det',
        ),
    ]
