# Generated by Django 3.0.7 on 2020-06-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0013_delete_exercise_det'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
