# Generated by Django 3.0.7 on 2020-06-20 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0005_auto_20200616_1625'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_chance', models.TimeField()),
                ('hour_lesson', models.TimeField()),
                ('hour_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_max', models.IntegerField(default=0)),
                ('cant_in', models.IntegerField(default=0)),
                ('quota', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('enable', models.BooleanField(default=True)),
                ('id_exercise_fk', models.ForeignKey(blank=True, db_column='id_exercise_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise')),
                ('id_hour_fk', models.ForeignKey(blank=True, db_column='id_hour_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_det.Hour')),
                ('id_user_fk', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
