# Generated by Django 3.0.7 on 2020-06-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0004_day_id_exercise_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='id_exercise_fk',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Hour',
        ),
    ]
