# Generated by Django 3.0.7 on 2020-06-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0006_lesson_det_day_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
