# Generated by Django 3.0.7 on 2020-06-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0008_auto_20200623_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='day_lesson',
            field=models.DateField(blank=True, null=True),
        ),
    ]
