# Generated by Django 3.0.7 on 2020-06-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_auto_20200623_1453'),
        ('lesson_det', '0009_auto_20200623_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='day_lesson',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lesson_det',
            name='id_exercise_fk',
            field=models.ForeignKey(db_column='id_exercise_fk', on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
    ]
