# Generated by Django 3.0.7 on 2020-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0010_auto_20200624_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='day_lesson',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson_det',
            name='hour_lesson',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
