# Generated by Django 3.0.7 on 2020-06-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0012_auto_20200624_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_det',
            name='saw',
            field=models.BooleanField(default=False),
        ),
    ]
