# Generated by Django 3.0.7 on 2020-06-24 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_det', '0013_lesson_det_saw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='id_user_fk',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
