# Generated by Django 3.0.7 on 2020-06-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20200627_0949'),
        ('lesson_det', '0014_auto_20200624_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='id_exercise_fk',
            field=models.ForeignKey(blank=True, db_column='id_exercise_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
    ]
