# Generated by Django 3.0.7 on 2020-07-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0015_auto_20200628_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='cant_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
