# Generated by Django 3.0.7 on 2020-08-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0016_auto_20200703_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_det',
            name='lesson_status',
            field=models.CharField(choices=[('notone', 'NOTONE'), ('open', 'OPEN'), ('close', 'CLOSE'), ('notchance', 'NOTCHANCE'), ('inprocess', 'INPROCESS'), ('finished', 'FINISHED')], default='notone', max_length=10),
        ),
    ]
