# Generated by Django 3.0.7 on 2020-08-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0018_auto_20200818_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='lesson_status',
            field=models.CharField(choices=[('NOTONE', 'NOTONE'), ('OPEN', 'OPEN'), ('close', 'CLOSE'), ('notchance', 'NOTCHANCE'), ('inprocess', 'INPROCESS'), ('finished', 'FINISHED')], default='NOTONE', max_length=10),
        ),
    ]
