# Generated by Django 3.0.7 on 2020-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0019_auto_20200818_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='lesson_status',
            field=models.CharField(choices=[('NOTONE', 'NOTONE'), ('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('NOTCHANCE', 'NOTCHANCE'), ('INPROCESS', 'INPROCESS'), ('FINISHED', 'FINISHED')], default='NOTONE', max_length=10),
        ),
    ]
