# Generated by Django 3.0.7 on 2020-08-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0020_auto_20200823_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_det',
            name='saw',
        ),
    ]
