# Generated by Django 3.0.7 on 2020-08-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0021_remove_lesson_det_saw'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_det',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
