# Generated by Django 3.0.7 on 2020-08-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0022_lesson_det_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='lesson_status',
            field=models.CharField(choices=[('RESERVAR', 'RESERVAR'), ('NO CHANCE', 'NO CHANCE'), ('EN CLASE', 'EN CLASE'), ('FINALIZADO', 'FINALIZADO')], default='RESERVAR', max_length=10),
        ),
    ]
