# Generated by Django 3.0.7 on 2020-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0023_auto_20200827_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_det',
            name='lesson_capacity_status',
            field=models.CharField(choices=[('VACIO', 'VACIO'), ('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], default='VACIO', max_length=10),
        ),
    ]
