# Generated by Django 3.0.7 on 2020-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0024_lesson_det_lesson_capacity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='lesson_status',
            field=models.CharField(choices=[('---', 'RESERVAR'), ('NO CHANCE', 'NO CHANCE'), ('EN CLASE', 'EN CLASE'), ('FINALIZADO', 'FINALIZADO')], default='---', max_length=10),
        ),
    ]
