# Generated by Django 3.0.7 on 2020-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0025_auto_20200830_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_det',
            name='lesson_status',
            field=models.CharField(choices=[('---', '---'), ('NO CHANCE', 'NO CHANCE'), ('EN CLASE', 'EN CLASE'), ('FINALIZADO', 'FINALIZADO')], default='---', max_length=10),
        ),
    ]
