# Generated by Django 3.0.7 on 2020-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolution', '0003_remove_devolution_id_lesson_fk'),
        ('lesson_det', '0026_auto_20200901_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_det',
            name='id_devolution_fk',
            field=models.ManyToManyField(blank=True, to='devolution.Devolution'),
        ),
    ]
