# Generated by Django 3.0.7 on 2020-09-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0027_lesson_det_id_devolution_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_det',
            name='id_devolution_fk',
        ),
    ]
