# Generated by Django 3.0.7 on 2020-09-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolution',
            name='cant_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devolution',
            name='cant_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
