# Generated by Django 3.0.7 on 2020-09-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devolution', '0002_auto_20200901_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolution',
            name='id_lesson_fk',
        ),
    ]
