# Generated by Django 3.0.7 on 2020-09-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0028_remove_lesson_det_id_devolution_fk'),
        ('devolution', '0003_remove_devolution_id_lesson_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolution',
            name='id_lesson_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_det.Lesson_det'),
        ),
    ]
