# Generated by Django 3.0.7 on 2020-09-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_det', '0028_remove_lesson_det_id_devolution_fk'),
        ('devolution', '0004_devolution_id_lesson_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolution',
            name='id_lesson_fk',
        ),
        migrations.AddField(
            model_name='devolution',
            name='id_lesson_fk',
            field=models.ManyToManyField(blank=True, to='lesson_det.Lesson_det'),
        ),
    ]
