# Generated by Django 3.0.7 on 2020-09-02 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0013_auto_20200627_0949'),
        ('devolution', '0005_auto_20200902_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolution',
            name='id_exercise_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AlterField(
            model_name='devolution',
            name='id_user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
