# Generated by Django 3.0.7 on 2020-09-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devolution', '0007_auto_20200902_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolution',
            name='selected',
        ),
    ]
