# Generated by Django 3.0.7 on 2020-09-07 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devolution', '0008_remove_devolution_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolution',
            name='id_user_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
