# Generated by Django 3.0.7 on 2020-09-07 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devolution', '0009_auto_20200907_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolution',
            name='id_user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
