# Generated by Django 3.0.7 on 2020-09-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolution', '0010_auto_20200907_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolution',
            name='id_lesson_before',
            field=models.IntegerField(default=0),
        ),
    ]
