# Generated by Django 3.0.7 on 2020-12-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20201208_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='SystemPilates',
        ),
    ]
