# Generated by Django 3.0.7 on 2020-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20201208_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempilates',
            name='delta_day',
            field=models.IntegerField(default=4),
        ),
    ]
