# Generated by Django 3.0.7 on 2020-12-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_systempilates_documentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systempilates',
            name='documentation',
        ),
        migrations.AddField(
            model_name='systempilates',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systempilates',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
