# Generated by Django 3.0.7 on 2020-12-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20201231_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('direction', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='systempilates',
            name='contact',
        ),
    ]
