# Generated by Django 3.0.7 on 2020-12-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20201231_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systempilates',
            old_name='rules',
            new_name='reglas',
        ),
    ]
