# Generated by Django 3.0.4 on 2020-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_id_exercise_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='oportunities',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='total_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
