# Generated by Django 3.0.4 on 2020-04-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20200421_1552'),
        ('plan', '0003_auto_20200422_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id_exercise_fk',
            field=models.ForeignKey(db_column='id_exercise_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
    ]
