# Generated by Django 3.0.6 on 2020-06-05 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20200429_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default="Ninguno", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='oportunities',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
