# Generated by Django 3.0.7 on 2020-06-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_plan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, default='Sin description asignada', null=True),
        ),
    ]
